[workspace]
members = ["sys"]
exclude = ["examples/full_usage"]

[package]
name = "whisper-rs"
version = "0.14.4"
edition = "2021"
description = "Rust bindings for whisper.cpp"
license = "Unlicense"
documentation = "https://docs.rs/whisper-rs"
repository = "https://codeberg.org/tazz4843/whisper-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whisper-rs-sys = { path = "sys", version = "0.13" }
log = { version = "0.4", optional = true }
tracing = { version = "0.1", optional = true }
libc = { version = "0.2", optional = true }

[dev-dependencies]
hound = "3.5.0"
rand = "0.8.4"

[features]
default = []

raw-api = []
coreml = ["whisper-rs-sys/coreml"]
cuda = ["whisper-rs-sys/cuda", "_gpu"]
hipblas = ["whisper-rs-sys/hipblas", "_gpu"]
openblas = ["whisper-rs-sys/openblas"]
metal = ["whisper-rs-sys/metal", "_gpu"]
vulkan = ["whisper-rs-sys/vulkan", "_gpu", "dep:libc"]
openmp = ["whisper-rs-sys/openmp"]
intel-sycl = ["whisper-rs-sys/intel-sycl", "_gpu"]
_gpu = []
test-with-tiny-model = []

# Bring logs into Rust via the log crate. *Warning*: not mutually exclusive with tracing_backend,
# will result in duplicate logs if both are enabled and one consumes logs from the other.
log_backend = ["dep:log"]

# Bring logs into Rust via the tracing crate. *Warning*: not mutually exclusive with log_backend,
# will result in duplicate logs if both are enabled and one consumes logs from the other.
tracing_backend = ["dep:tracing"]
